on: [push]

name: Datadog Static Analysis

# Use restritive workflow permissions. See https://datadoghq.atlassian.net/wiki/spaces/SECENG/pages/3913581900/GitHub+Workflow+Token+Permissions+GITHUB_TOKEN#Approach-1%3A-Bottom-up-%E2%A4%B4%EF%B8%8F
permissions:
  contents: read
  packages: read
  
jobs:
  static-analysis:
    runs-on: ubuntu-latest
    name: Datadog Static Analyzer
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Check code meets quality and security standards
      id: datadog-static-analysis
      uses: DataDog/datadog-static-analyzer-github-action@v1
      with:
        dd_api_key: ${{ secrets.DD_STATIC_ANALYSIS_API_KEY }}
        dd_app_key: ${{ secrets.DD_STATIC_ANALYSIS_APP_KEY }}
        dd_service: integration-core
        dd_env: ci
        dd_site: datadoghq.com
        cpu_count: 2
