name: Permissions Advisor


# Use restritive workflow permissions. See https://datadoghq.atlassian.net/wiki/spaces/SECENG/pages/3913581900/GitHub+Workflow+Token+Permissions+GITHUB_TOKEN#Approach-1%3A-Bottom-up-%E2%A4%B4%EF%B8%8F
permissions:
  actions: read
  contents: read
  packages: read
  
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'The name of the workflow file to analyze'
        required: true
        type: string
      count:
        description: 'How many last runs to analyze'
        required: false
        type: number
        default: 10

jobs:
  advisor:
    runs-on: ubuntu-latest
    steps:
    - uses: GitHubSecurityLab/actions-permissions/advisor@v1
      with:
        name: ${{ inputs.name }}
        count: ${{ inputs.count }}