name: Check PR

on:
  pull_request_target:
    types: [opened, labeled, unlabeled, synchronize]

# Use restritive workflow permissions. See https://datadoghq.atlassian.net/wiki/spaces/SECENG/pages/3913581900/GitHub+Workflow+Token+Permissions+GITHUB_TOKEN#Approach-1%3A-Bottom-up-%E2%A4%B4%EF%B8%8F
permissions:
  contents: read
  packages: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  run:
    uses: ./.github/workflows/pr-quick-check.yml
    if: ${{ github.base_ref == 'master' }}
    with:
      repo: core
    secrets: inherit
