name: Publish test results for PRs

on:
  workflow_run:
    workflows:
    - PR
    - PR All
    types:
    - completed

# Use restritive workflow permissions. See https://datadoghq.atlassian.net/wiki/spaces/SECENG/pages/3913581900/GitHub+Workflow+Token+Permissions+GITHUB_TOKEN#Approach-1%3A-Bottom-up-%E2%A4%B4%EF%B8%8F
permissions:
  contents: read
  packages: read

jobs:
  publish:
    uses: ./.github/workflows/test-results-pr.yml
    if: github.event.workflow_run.conclusion != 'skipped'
    permissions:
      checks: write
      pull-requests: write
    secrets: inherit
