name: Save GitHub event

on:
  workflow_call:
    inputs:
      retention-days:
        required: false
        default: 1
        type: number

              
# Use restritive workflow permissions. See https://datadoghq.atlassian.net/wiki/spaces/SECENG/pages/3913581900/GitHub+Workflow+Token+Permissions+GITHUB_TOKEN#Approach-1%3A-Bottom-up-%E2%A4%B4%EF%B8%8F
permissions:
  contents: read
  packages: read
  
jobs:
  save-event:
    name: Save event
    runs-on: ubuntu-22.04

    steps:
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: github-event
        path: ${{ github.event_path }}
        retention-days: ${{ inputs.retention-days }}
