name: Weekly latest product version tests

on:
  schedule:
  # Weekly on Sunday night (America/New_York)
  - cron: "0 5 * * 1"
  pull_request: # DELETEME: Remove this  after testing
    branches:
      - main
      
# Use restritive workflow permissions. See https://datadoghq.atlassian.net/wiki/spaces/SECENG/pages/3913581900/GitHub+Workflow+Token+Permissions+GITHUB_TOKEN#Approach-1%3A-Bottom-up-%E2%A4%B4%EF%B8%8F
permissions:
  contents: read
  packages: read

jobs:
  test:
    uses: ./.github/workflows/test-all.yml
    with:
      repo: core

      # Options
      latest: true
    secrets: inherit

  submit-traces:
    needs:
    - test
    if: success() || failure()

    uses: ./.github/workflows/submit-traces.yml
    secrets: inherit
